### ISSUE TITLE
Did you EVER run/test this thing?  

### ISSUE THREAD

**Issue by javadba** [intel-analytics/TopicModeling#11]
The OnlineHDPOptimizer does not even extend LDAOptimizer.  **How can this possibly work ??!**

**Comment by hhbyyh** [comment]
OnlineHDPOptimizer was developed even before Spark has LDAOptimizer. We developed both OnlineLDA and OnlineHDP algorithm on Spark. OnlineLDA was merged into Spark and OnlineHDP was not. 

We stopped for OnlineHDP since we didn't get enough user interests/requirements to support further development. The code was left as it is, to provide reference for anyone with interests.

**Comment by javadba** [comment]
There is no way shown to run the OnlineHDPOptimizer. Do you have any old repo/code that allows it to be used?
